# floorFlora — пол (сгенерировано в редакторе объектов)
basedir=./

img[floorflora][N] = floorflora_N.png
img[floorflora][E] = floorflora_E.png
img[floorflora][S] = floorflora_S.png
img[floorflora][W] = floorflora_W.png

walkable[floorflora]        = true
speedMultiplier[floorflora] = 1.0
damagePerSecond[floorflora] = 0.0
