# floorFlora3 — пол (сгенерировано в редакторе объектов)
basedir=./

img[floorflora3][N] = floorflora3_N_2.png
img[floorflora3][E] = floorflora3_E_2.png
img[floorflora3][S] = floorflora3_S_2.png
img[floorflora3][W] = floorflora3_W_2.png

walkable[floorflora3]        = true
speedMultiplier[floorflora3] = 1.0
damagePerSecond[floorflora3] = 0.0
