# floorFlora2 — пол (сгенерировано в редакторе объектов)
basedir=./

img[floorflora2][N] = floorflora2_N_2.png
img[floorflora2][E] = floorflora2_E_2.png
img[floorflora2][S] = floorflora2_S_2.png
img[floorflora2][W] = floorflora2_W_2.png

walkable[floorflora2]        = true
speedMultiplier[floorflora2] = 1.0
damagePerSecond[floorflora2] = 0.0
