# barrel — объект (сгенерировано в редакторе объектов)
basedir=./

# default
img[default][0] = default_0.png
img[default][90] = default_90.png
img[default][180] = default_180.png
img[default][270] = default_270.png

# object properties
collision  = true
layer      = 0
isometric  = true
drawWidth  = -1
drawHeight = -1
fitToCell  = true
fitScale   = 1.4
xOffset    = 0
yOffset    = 30
