# glass — пол (сгенерировано в редакторе объектов)
basedir=./

img[glass][N] = glass_N.png
img[glass][E] = glass_E.png
img[glass][S] = glass_S.png
img[glass][W] = glass_W.png

walkable[glass]        = true
speedMultiplier[glass] = 1.0
damagePerSecond[glass] = 0.0
